# ==== Paths and files ====

# The path to the data that will be used for the plot (default: data/wandb_exports).
runs_path: data/wandb_exports

# The name of the files that contain the scalars and the config
file_scalars: scalars.csv
file_config: config.yaml



# ==== Data selection ====
# The metric that will be used for the plot.
metric: -metrics.n_agents + metrics.n_plants * 2 +10000

# The filters that will be applied to the config for accepting a run.
# This will be done with an 'eval' function, so you can use any python code.
# filters:
  # - config.benchmark_name == 'bench16_fp_hc'

# The groupings that will be applied to the config for grouping the runs.
# It is composed of a list of python expressions that will be evaluated.
# The data will be grouped by the unique values of the tuple expression.
grouping:
  - config.benchmark_name
  # - config.env.variability_fruits

# The methods to use for aggregation (solid line) and error bars (shaded area).
method_aggregate: median # among mean, median, min, max
method_error: range # among std, sem, range, iqr, percentile_<q>, none
n_samples_shown: 0

# The maximum number of runs to load
max_n_runs: 2555

# The x-axis (default: _step).
x_axis: _step



# ==== Plotting interface options ====
# Label to use if no grouping, as a function of run_name and config.
label_individual: config.seed
# Label to use if grouping, as a function of config. If null, will use the grouping values.
label_group: config.seed
# The x-limits of the plot. By default it will be the min and max of the x-axis metric. 
x_lim: null
y_lim: null
# Whether to try adding y=0 to the limits if 0 is not too far away from the data (nearest than the data range).
do_try_include_y0: True
ratio_near_y0: 0.5 # The ratio of the data range that should be considered as "near" 0.
# Whether to do grid on the plot and the grid configuration.
do_grid: True
kwargs_grid:
  visible: ${do_grid}
# The alpha of the shaded area.
alpha_shaded: 0.1
# The maximum legend length. If the legend is longer, it will be cut.
max_legend_length: 522
# The kwargs for the plot function that will be used for grouping.
groups_plot_kwargs:
  - key: linestyle
    args: ['-', '--', '-.', ':']
  - key: color
    args: ['green', 'brown', 'blue', 'orange', 'red', 'brown', 'pink', 'gray', 'olive', 'cyan']
# Which color to use by default (if not specified in the groups_plot_kwargs)
default_plot_kwargs: 
  color : 'black'
  linestyle: '-'

# ==== Hydra config (do not change) ====

# Defaults sub-configs and other Hydra config.
defaults:
  - _self_
  - override hydra/hydra_logging: default  
  - override hydra/job_logging: stdout 

# Hydra config, do not change.
hydra:
  output_subdir: null
  run:
    dir: .
  