# The path to the data that will be used for the plot (default: data/wandb_exports).
runs_path: data/wandb_exports

# The metric that will be used for the plot.
metric: n_agents

# The filters that will be applied to the config for accepting a run.
# This will be done with an 'eval' function, so you can use any python code.
filters:
  - "config.benchmark_name == 'bench16_fp_hc'"
# The groupings that will be applied to the config for grouping the runs.
# It is composed of a list of python expressions that will be evaluated.
# The data will be grouped by the unique values of the tuple expression.
grouping:
  - "config.env.variability_fruits"

# The x-limits of the plot. By default it will be the min and max of the x-axis metric. 
x_lim: null
y_lim: null



# Defaults sub-configs and other Hydra config.
defaults:
  - _self_
  - override hydra/hydra_logging: default  
  - override hydra/job_logging: stdout 


# Hydra config, do not change.
hydra:
  output_subdir: null
  run:
    dir: .
  